import 'dart:io';
import 'package:mason/mason.dart';

Future<void> run(HookContext context) async {
  final name = context.vars['name'] as String;
  final bundleId = context.vars['bundle_id'] as String;
  final platforms = (context.vars['platforms'] as List).cast<String>();
  final useFirebase = context.vars['use_firebase'] as bool;

  // 1. Scaffold the Flutter project
  _run(context, 'flutter create', [
    'flutter', 'create',
    '--platforms=${platforms.join(',')}',
    '--org=${_orgPrefix(bundleId)}',
    '.',
  ]);

  // 2. Remove the default entry point generated by flutter create
  _deleteFile(context, 'lib/main.dart');

  // 3. Replace the generated widget test with a project-aware smoke test
  _updateWidgetTest(context, name);

  // 4. Install dependencies
  _run(context, 'flutter pub get', ['flutter', 'pub', 'get']);

  // 5. Regenerate type-safe locale keys from translation files
  _run(
    context,
    'Generate locale keys',
    [
      'flutter', 'pub', 'run', 'easy_localization:generate',
      '-f', 'keys',
      '-o', 'locale_keys.dart',
      '-S', 'assets/translations/',
      '-O', 'lib/core/app/localization',
    ],
    fatal: false,
  );

  // 6. Generate native splash screen assets
  _run(
    context,
    'Set up native splash',
    ['dart', 'run', 'flutter_native_splash:create'],
    fatal: false,
  );

  // 7. Set the bundle ID across all target platforms
  _run(context, 'Activate rename', [
    'flutter', 'pub', 'global', 'activate', 'rename',
  ]);
  _run(context, 'Set bundle ID', [
    'rename', 'setBundleId',
    '--targets', platforms.join(','),
    '--value', bundleId,
  ]);

  // 8. Inject supported locales into the iOS plist
  if (platforms.contains('ios')) {
    _addCFBundleLocalizations(context);
  }

  // 9. Install flutter-skill MCP server if not already on PATH
  _ensureFlutterSkill(context);

  // 10. Configure Firebase interactively
  if (useFirebase) {
    final confirmed = context.logger.confirm(
      'Run `flutterfire configure` now? (requires Firebase CLI + login)',
      defaultValue: true,
    );
    if (confirmed) {
      _run(context, 'Activate flutterfire_cli', [
        'dart', 'pub', 'global', 'activate', 'flutterfire_cli',
      ]);
      await _runInteractive(context, 'flutterfire configure', [
        'flutterfire', 'configure',
        '--platforms=${_firebasePlatforms(platforms).join(',')}',
      ]);
    } else {
      _createDummyFirebaseOptions(context);
    }
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

void _ensureFlutterSkill(HookContext context) {
  final check = Process.runSync(
    'flutter-skill', ['--version'],
    runInShell: true,
  );
  if (check.exitCode == 0) return;

  final progress = context.logger.progress('Install flutter-skill');
  final result = Process.runSync(
    'npm', ['install', '-g', 'flutter-skill'],
    runInShell: true,
  );
  if (result.exitCode == 0) {
    progress.complete('Installed flutter-skill');
  } else {
    progress.fail('flutter-skill install failed');
    context.logger.warn(
      'Install manually: npm install -g flutter-skill',
    );
  }
}

String _orgPrefix(String bundleId) {
  return bundleId.contains('.')
      ? bundleId.substring(0, bundleId.lastIndexOf('.'))
      : bundleId;
}

void _deleteFile(HookContext context, String path) {
  final file = File(path);
  if (!file.existsSync()) return;
  file.deleteSync();
  context.logger.success('Removed $path.');
}

void _addCFBundleLocalizations(HookContext context) {
  final locales = _localesFromFile();
  final plist = File('ios/Runner/Info.plist');

  if (!plist.existsSync()) {
    context.logger.warn('Info.plist not found — skipping CFBundleLocalizations.');
    return;
  }

  var content = plist.readAsStringSync();
  if (content.contains('CFBundleLocalizations')) {
    context.logger.info('CFBundleLocalizations already present — skipping.');
    return;
  }

  final entries = locales.map((l) => '\t\t<string>$l</string>').join('\n');
  final block =
      '\t<key>CFBundleLocalizations</key>\n\t<array>\n$entries\n\t</array>';

  plist.writeAsStringSync(
    content.replaceFirst(
      '</dict>\n</plist>',
      '$block\n</dict>\n</plist>',
    ),
  );

  context.logger.success('Info.plist — added CFBundleLocalizations: $locales.');
}

/// Extracts locale codes from AppLocale enum entries in localization.dart.
List<String> _localesFromFile() {
  final file = File('lib/core/app/localization/localization.dart');
  if (!file.existsSync()) return ['en'];

  final matches = RegExp(r"Locale\('(\w+)'\)")
      .allMatches(file.readAsStringSync())
      .map((m) => m.group(1)!)
      .toList();

  return matches.isEmpty ? ['en'] : matches;
}

void _updateWidgetTest(HookContext context, String name) {
  final packageName = _toSnakeCase(name);
  final className = _toPascalCase(name);

  final testFile = File('test/widget_test.dart');
  if (!testFile.existsSync()) {
    context.logger.warn('test/widget_test.dart not found — skipping.');
    return;
  }

  testFile.writeAsStringSync(
    "import 'package:flutter_test/flutter_test.dart';\n"
    "import 'package:$packageName/environment/main.dart';\n"
    '\n'
    'void main() {\n'
    "  testWidgets('smoke test', (WidgetTester tester) async {\n"
    '    await tester.pumpWidget(const $className());\n'
    '  });\n'
    '}\n',
  );

  context.logger.success('Updated test/widget_test.dart.');
}

String _toSnakeCase(String name) => name
    .replaceAll(RegExp(r'[\s\-]+'), '_')
    .replaceAllMapped(RegExp(r'([a-z])([A-Z])'), (m) => '${m[1]}_${m[2]}')
    .toLowerCase();

String _toPascalCase(String name) => name
    .split(RegExp(r'[\s_\-]+'))
    .map((w) => w.isEmpty ? '' : w[0].toUpperCase() + w.substring(1))
    .join();

/// Filters to platforms supported by flutterfire_cli.
List<String> _firebasePlatforms(List<String> platforms) {
  const supported = {'android', 'ios', 'macos', 'web'};
  return platforms.where(supported.contains).toList();
}

/// Creates a placeholder lib/firebase_options.dart that compiles cleanly.
/// Matches the exact shape flutterfire_cli generates so no call sites break.
/// The developer replaces it by running `flutterfire configure`.
void _createDummyFirebaseOptions(HookContext context) {
  File('lib/firebase_options.dart').writeAsStringSync(
    "// PLACEHOLDER — run `flutterfire configure` to replace this file.\n"
    '// ignore_for_file: type=lint\n'
    "import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;\n"
    "import 'package:flutter/foundation.dart'\n"
    '    show defaultTargetPlatform, kIsWeb, TargetPlatform;\n'
    '\n'
    'class DefaultFirebaseOptions {\n'
    '  static FirebaseOptions get currentPlatform {\n'
    '    if (kIsWeb) return web;\n'
    '    switch (defaultTargetPlatform) {\n'
    '      case TargetPlatform.android:\n'
    '        return android;\n'
    '      case TargetPlatform.iOS:\n'
    '        return ios;\n'
    '      case TargetPlatform.macOS:\n'
    '        return macos;\n'
    '      default:\n'
    "        throw UnsupportedError('Unsupported platform — run `flutterfire configure`.');\n"
    '    }\n'
    '  }\n'
    '\n'
    '  static const FirebaseOptions android = FirebaseOptions(\n'
    "    apiKey: 'PLACEHOLDER',\n"
    "    appId: 'PLACEHOLDER',\n"
    "    messagingSenderId: 'PLACEHOLDER',\n"
    "    projectId: 'PLACEHOLDER',\n"
    '  );\n'
    '\n'
    '  static const FirebaseOptions ios = FirebaseOptions(\n'
    "    apiKey: 'PLACEHOLDER',\n"
    "    appId: 'PLACEHOLDER',\n"
    "    messagingSenderId: 'PLACEHOLDER',\n"
    "    projectId: 'PLACEHOLDER',\n"
    '  );\n'
    '\n'
    '  static const FirebaseOptions macos = FirebaseOptions(\n'
    "    apiKey: 'PLACEHOLDER',\n"
    "    appId: 'PLACEHOLDER',\n"
    "    messagingSenderId: 'PLACEHOLDER',\n"
    "    projectId: 'PLACEHOLDER',\n"
    '  );\n'
    '\n'
    '  static const FirebaseOptions web = FirebaseOptions(\n'
    "    apiKey: 'PLACEHOLDER',\n"
    "    appId: 'PLACEHOLDER',\n"
    "    messagingSenderId: 'PLACEHOLDER',\n"
    "    projectId: 'PLACEHOLDER',\n"
    '  );\n'
    '}\n',
  );

  context.logger.info(
    'Created placeholder lib/firebase_options.dart — replace it by running `flutterfire configure`.',
  );
}

/// Runs a command with stdio inherited so the user can interact with it.
Future<void> _runInteractive(
  HookContext context,
  String label,
  List<String> command,
) async {
  context.logger.info('$label — follow the prompts below:');
  final process = await Process.start(
    command.first,
    command.skip(1).toList(),
    mode: ProcessStartMode.inheritStdio,
    runInShell: true,
  );
  final exitCode = await process.exitCode;
  if (exitCode != 0) {
    context.logger.warn(
      '$label failed. Run `flutterfire configure` manually to generate lib/firebase_options.dart.',
    );
  }
}

void _run(
  HookContext context,
  String label,
  List<String> command, {
  bool fatal = true,
}) {
  final progress = context.logger.progress(label);
  final result = Process.runSync(
    command.first,
    command.skip(1).toList(),
    runInShell: true,
  );

  if (result.exitCode != 0) {
    progress.fail('$label failed (exit ${result.exitCode})');
    final stderr = result.stderr.toString().trim();
    if (stderr.isNotEmpty) context.logger.err(stderr);
    if (fatal) exit(result.exitCode);
    return;
  }

  progress.complete(label);
}
